In [2]:
import numpy as np

In [3]:
mylist = [1,2,3,4]

In [4]:
my_array = np.array(mylist)

In [5]:
my_array

array([1, 2, 3, 4])

In [6]:
my_list2= [11,22,33,44]

In [7]:
mylists = [mylist, my_list2]

In [8]:
mylists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(mylists)

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
5/2

2.5

In [13]:
from __future__ import division

In [14]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [15]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [16]:
arr1 *arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [17]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
1/arr1


array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [19]:
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [29]:
arr = np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr[0:5]= 100

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice_arr = arr[0:6]

In [32]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [33]:
slice_arr[:] = 99

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr_copy = arr.copy()

In [36]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [38]:
arr_2d[1][1]

25

In [39]:
arr_2d[1,2]

30

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr_2d[2]

array([35, 40, 45])

In [43]:
arr_2d[2,:]

array([35, 40, 45])

In [44]:
arr2d = np.zeros((10,10))

In [45]:
arr_length= arr2d.shape[1]

In [47]:
for i in range(arr_length):
    arr2d[i] = i

In [48]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [49]:
for i in range(arr_length):
    for j in range(arr_length):
        arr2d[i,j] = i,j

ValueError: setting an array element with a sequence.

In [50]:
arr2d[[2,4,7]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [53]:
arr2d[[4,5,5,4]]

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [54]:
for i in range(arr_length):
    for j in range(arr_length):
        arr2d[i][j] = i,j

ValueError: setting an array element with a sequence.