In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv('../data/50_Startups.csv')

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [8]:
X[0:3,:]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida']], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
labelencoder_X = LabelEncoder()

In [13]:
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoeder = OneHotEncoder(categorical_features=[3])
X = onehotencoeder.fit_transform(X).toarray()

/home/ma/bin/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/ma/bin/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [14]:
X[0:3, :]

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05]])

In [16]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

In [17]:
np.set_printoptions(suppress=True)

In [18]:
X[0:3, :]

array([[     0.  ,      0.  ,      1.  , 165349.2 , 136897.8 , 471784.1 ],
       [     1.  ,      0.  ,      0.  , 162597.7 , 151377.59, 443898.53],
       [     0.  ,      1.  ,      0.  , 153441.51, 101145.55, 407934.54]])

## avoidings dummy v trap

In [19]:
X = X[:, 1:]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,
                                                   random_state = 0)

In [23]:
len(X_train)

40

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
regressor = LinearRegression()

In [26]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

## predictions

In [28]:
y_pred = regressor.predict(X_test)

In [29]:
y_pred

array([103015.20159795, 132582.27760817, 132447.73845176,  71976.09851257,
       178537.48221058, 116161.24230165,  67851.69209675,  98791.73374686,
       113969.43533013, 167921.06569553])

In [30]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

## backword elumination

In [31]:
import statsmodels.formula.api as sm

In [35]:
X = np.append(arr= np.ones((50,1)).astype(int), values=X, axis=1)

In [36]:
X[0:3, :]

array([[     1.  ,      0.  ,      1.  , 165349.2 , 136897.8 , 471784.1 ,
             1.  ],
       [     1.  ,      0.  ,      0.  , 162597.7 , 151377.59, 443898.53,
             1.  ],
       [     1.  ,      1.  ,      0.  , 153441.51, 101145.55, 407934.54,
             1.  ]])