In [54]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression as LR

In [55]:
train = pd.read_csv("obent/train.csv")

In [56]:
test= pd.read_csv("obent/test.csv")
sample = pd.read_csv("obent/sample.csv",header=None)

In [57]:
train.head()

datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather precipitation  temperature  
0      快晴            --         19.8  
1      快晴            --         17.0  
2      快晴            --         15.5  
3      快晴            --         15.2  
4      快晴            --         16.1

In [58]:
trainX=train["temperature"]
y = train["y"]

In [59]:
trainX

0      19.8
1      17.0
2      15.5
3      15.2
4      16.1
5      14.6
6      17.9
7      14.7
8      17.7
9      12.1
10     13.8
11     13.9
12     13.5
13     13.8
14     14.9
15      9.1
16      7.1
17     11.0
18     12.3
19     13.9
20     11.3
21     10.8
22      7.8
23      6.8
24      8.4
25     11.5
26      8.0
27      7.3
28      7.3
29      9.8
       ... 
177    32.2
178    33.3
179    33.3
180    33.0
181    33.1
182    26.0
183    26.2
184    21.0
185    21.6
186    25.1
187    23.4
188    29.1
189    26.7
190    26.5
191    30.2
192    23.1
193    26.8
194    25.0
195    21.9
196    27.3
197    28.8
198    25.0
199    24.1
200    23.6
201    25.2
202    24.8
203    25.4
204    27.1
205    26.6
206    28.1
Name: temperature, Length: 207, dtype: float64

In [60]:
testX = test["temperature"]

In [61]:
trainX= trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [62]:
trainX

array([[19.8],
       [17. ],
       [15.5],
       [15.2],
       [16.1],
       [14.6],
       [17.9],
       [14.7],
       [17.7],
       [12.1],
       [13.8],
       [13.9],
       [13.5],
       [13.8],
       [14.9],
       [ 9.1],
       [ 7.1],
       [11. ],
       [12.3],
       [13.9],
       [11.3],
       [10.8],
       [ 7.8],
       [ 6.8],
       [ 8.4],
       [11.5],
       [ 8. ],
       [ 7.3],
       [ 7.3],
       [ 9.8],
       [10.9],
       [ 5.1],
       [ 5.8],
       [ 2.9],
       [ 7. ],
       [ 7.8],
       [ 6.5],
       [10.4],
       [ 7.4],
       [ 8.5],
       [10.1],
       [ 5.1],
       [12.6],
       [10.3],
       [15.3],
       [14.1],
       [15.9],
       [ 3.8],
       [ 3. ],
       [ 4.2],
       [ 5.5],
       [ 7.8],
       [ 6.3],
       [ 6.4],
       [ 1.2],
       [11.6],
       [ 6.8],
       [ 7.3],
       [ 5.4],
       [ 8.5],
       [ 6.6],
       [10.5],
       [11.5],
       [ 8.5],
       [17.7],
       [ 7.8],
       [ 8

In [63]:
model1 = LR()

In [64]:
model1.fit(trainX,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [65]:
model1.coef_

array([-2.5023821])

In [66]:
model1.intercept_

134.79948383749925

In [67]:
pred = model1.predict(testX)

In [68]:
pred

array([ 84.25136537,  74.99255159,  62.9811175 ,  80.99826864,
        79.49683938,  76.49398085,  78.49588653,  69.48731097,
        67.73564349,  95.76232304,  88.25517673,  77.24469548,
        74.99255159,  84.25136537,  96.01256125,  98.01446693,
        88.00493852,  77.99541011,  87.00398568,  85.75279463,
        85.75279463,  87.75470031,  87.5044621 ,  94.7613702 ,
        86.75374747,  84.50160358,  81.74898327,  98.01446693,
        98.76518156,  86.00303284,  95.26184662,  99.01541977,
        94.51113199,  97.51399051, 108.52447176,  97.51399051,
       106.27232787, 111.7775685 ,  97.01351409,  96.51303767])

In [69]:
sample.head()

0   1
0  2014-10-1  24
1  2014-10-2  71
2  2014-10-3  25
3  2014-10-6  32
4  2014-10-7  60

In [70]:
sample[1]=pred

In [71]:
sample.head()

0          1
0  2014-10-1  84.251365
1  2014-10-2  74.992552
2  2014-10-3  62.981117
3  2014-10-6  80.998269
4  2014-10-7  79.496839

In [72]:
sample.to_csv('submit1.csv', index=None, header=None)

In [73]:
train.isnull().sum()

datetime           0
y                  0
week               0
soldout            0
name               0
kcal              41
remarks          186
event            193
payday           197
weather            0
precipitation      0
temperature        0
dtype: int64

In [74]:
test.isnull().sum()

datetime          0
week              0
soldout           0
name              0
kcal              4
remarks          33
event            37
payday           38
weather           0
precipitation     0
temperature       0
dtype: int64

In [75]:
avg = train['kcal'].mean()

In [76]:
avg

404.4096385542169

In [79]:
trainX = train['kcal'].fillna(avg)
testX = test['kcal'].fillna(avg)

In [80]:
trainX

0      404.409639
1      404.409639
2      404.409639
3      404.409639
4      404.409639
5      404.409639
6      404.409639
7      404.409639
8      404.409639
9      404.409639
10     404.409639
11     404.409639
12     404.409639
13     404.409639
14     404.409639
15     404.409639
16     404.409639
17     404.409639
18     404.409639
19     404.409639
20     404.409639
21     404.409639
22     404.409639
23     404.409639
24     404.409639
25     404.409639
26     404.409639
27     404.409639
28     404.000000
29     462.000000
          ...    
177    396.000000
178    385.000000
179    423.000000
180    405.000000
181    404.409639
182    412.000000
183    400.000000
184    410.000000
185    396.000000
186    398.000000
187    380.000000
188    440.000000
189    408.000000
190    405.000000
191    380.000000
192    385.000000
193    460.000000
194    450.000000
195    385.000000
196    404.409639
197    438.000000
198    430.000000
199    395.000000
200    400.000000
201    395

In [81]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [83]:
trainX[:3]

array([[404.40963855],
       [404.40963855],
       [404.40963855]])

In [84]:
y = train['y']

In [86]:
model2 = LR()

In [87]:
model2.fit(trainX, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [89]:
model2.coef_

array([0.13195178])

In [91]:
model2.intercept_

33.26061577029441

In [92]:
pred2 = model2.predict(testX)

In [93]:
pred2

array([88.68036439, 88.02060548, 86.70108765, 86.04132874, 89.99988221,
       88.68036439, 90.65964112, 86.62318841, 87.096943  , 92.63891786,
       86.04132874, 88.02060548, 89.47207508, 87.36084656, 88.02060548,
       89.73597865, 86.62318841, 86.96499122, 89.3401233 , 89.99988221,
       89.47207508, 90.79159291, 91.31940004, 89.3401233 , 87.36084656,
       86.62318841, 87.62475013, 89.47207508, 88.41646082, 85.51352161,
       89.60402686, 90.39573756, 87.22889478, 89.99988221, 88.81231617,
       86.62318841, 93.95843568, 88.02060548, 88.68036439, 88.15255726])

In [95]:
sample[1] = pred2

In [96]:
sample

0          1
0    2014-10-1  88.680364
1    2014-10-2  88.020605
2    2014-10-3  86.701088
3    2014-10-6  86.041329
4    2014-10-7  89.999882
5    2014-10-8  88.680364
6    2014-10-9  90.659641
7   2014-10-10  86.623188
8   2014-10-14  87.096943
9   2014-10-15  92.638918
10  2014-10-16  86.041329
11  2014-10-17  88.020605
12  2014-10-20  89.472075
13  2014-10-21  87.360847
14  2014-10-22  88.020605
15  2014-10-23  89.735979
16  2014-10-24  86.623188
17  2014-10-27  86.964991
18  2014-10-28  89.340123
19  2014-10-29  89.999882
20  2014-10-30  89.472075
21  2014-10-31  90.791593
22   2014-11-4  91.319400
23   2014-11-5  89.340123
24   2014-11-6  87.360847
25   2014-11-7  86.623188
26  2014-11-10  87.624750
27  2014-11-11  89.472075
28  2014-11-12  88.416461
29  2014-11-13  85.513522
30  2014-11-14  89.604027
31  2014-11-17  90.395738
32  2014-11-18  87.228895
33  2014-11-19  89.999882
34  2014-11-20  88.812316
35  2014-11-21  86.623188
36  2014-11-25  93.958436
37  2014-11-26  88.020605
38  2014-11-27  88.680364
39  2014-11-28  88.152557