In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression as LR

In [41]:
train = pd.read_csv('obent/train.csv')
test = pd.read_csv('obent/test.csv')
sample = pd.read_csv('obent/sample.csv', header=None)

In [25]:
trainX = train['temperature']
y = train['y']

In [26]:
y

0       90
1      101
2      118
3      120
4      130
      ... 
202     59
203     50
204     45
205     56
206     40
Name: y, Length: 207, dtype: int64

In [27]:
testX = test['temperature']

In [28]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [29]:
model1 = LR()

In [30]:
model1.fit(trainX, y)

LinearRegression()

In [31]:
model1.coef_

array([-2.5023821])

In [32]:
model1.intercept_

134.79948383749922

In [35]:
predicted = model1.predict(testX)

In [36]:
predicted

array([ 84.25136537,  74.99255159,  62.9811175 ,  80.99826864,
        79.49683938,  76.49398085,  78.49588653,  69.48731097,
        67.73564349,  95.76232304,  88.25517673,  77.24469548,
        74.99255159,  84.25136537,  96.01256125,  98.01446693,
        88.00493852,  77.99541011,  87.00398568,  85.75279463,
        85.75279463,  87.75470031,  87.5044621 ,  94.7613702 ,
        86.75374747,  84.50160358,  81.74898327,  98.01446693,
        98.76518156,  86.00303284,  95.26184662,  99.01541977,
        94.51113199,  97.51399051, 108.52447176,  97.51399051,
       106.27232787, 111.7775685 ,  97.01351409,  96.51303767])

In [42]:
sample.head()


0   1
0  2014-10-1  24
1  2014-10-2  71
2  2014-10-3  25
3  2014-10-6  32
4  2014-10-7  60

In [43]:
sample[1] = predicted

In [44]:
sample.head()

0          1
0  2014-10-1  84.251365
1  2014-10-2  74.992552
2  2014-10-3  62.981117
3  2014-10-6  80.998269
4  2014-10-7  79.496839

In [45]:
sample.to_csv("submit.csv", header=None, index=None)

In [46]:
train['week'].value_counts()

水    43
木    43
火    41
金    41
月    39
Name: week, dtype: int64

In [47]:
train['week'].unique()

array(['月', '火', '水', '木', '金'], dtype=object)

In [48]:
pd.get_dummies(train['week'])

月  木  水  火  金
0    1  0  0  0  0
1    0  0  0  1  0
2    0  0  1  0  0
3    0  1  0  0  0
4    0  0  0  0  1
..  .. .. .. .. ..
202  0  0  1  0  0
203  0  1  0  0  0
204  0  0  0  0  1
205  1  0  0  0  0
206  0  0  0  1  0

[207 rows x 5 columns]

In [59]:
trainX = pd.get_dummies(train[['week', 'temperature']])
testX = pd.get_dummies(test[['week','temperature']])

In [51]:
trainX.head()

temperature  week_月  week_木  week_水  week_火  week_金
0         19.8       1       0       0       0       0
1         17.0       0       0       0       1       0
2         15.5       0       0       1       0       0
3         15.2       0       1       0       0       0
4         16.1       0       0       0       0       1

In [52]:
y = train['y']

In [53]:
model2 = LR()

In [54]:
model2.fit(trainX, y)

LinearRegression()

In [55]:
model2.coef_

array([-2.53878074,  8.26339936, -9.47240196, -2.02873774,  1.85251984,
        1.38522051])

In [56]:
model2.intercept_

135.69119841401601

In [60]:
predicted = model2.predict(testX)