In [1]:
import numpy as np

In [2]:
a = np.array([3,4,5])

In [3]:
b = np.array([1,3,6])

In [4]:
np.dot(a, b)

45

In [5]:
a.dot(b)

45

## matrix

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
X = np.matrix([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])

In [9]:
X

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 3, 4, 5],
        [6, 7, 8, 9]])

In [10]:
X.shape

(4, 4)

In [11]:
A = np.array([[1,2],[3,4]])

In [13]:
B = np.array([[5,6],[7,8]])

In [14]:
A - B

array([[-4, -4],
       [-4, -4]])

In [15]:
A *B

array([[ 5, 12],
       [21, 32]])

In [16]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [18]:
A.mean()

2.5

In [19]:
np.matmul(B,A)

array([[23, 34],
       [31, 46]])

In [20]:
A = np.matrix([[1,2,3],[4,5,6]])

In [21]:
B = np.matrix([[7,8],[9,10],[11,12]])

In [22]:
np.matmul(A,B)

matrix([[ 58,  64],
        [139, 154]])

In [23]:
A.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [24]:
np.transpose(B)

matrix([[ 7,  9, 11],
        [ 8, 10, 12]])

In [25]:
B

matrix([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [26]:
A = np.matrix([[5,4,8],[3,0,9],[3, 4, 2]])

In [27]:
b = np.matrix([[2],[3],[4]])

## Linear independence

In [28]:
A = [[1,3, 1],[2,2,1],[3,1,1]]

In [29]:
from numpy import linalg as LA

In [30]:
x = np.matrix([[1,3,1],[2,2,1],[3,5,3]])

In [31]:
LA.matrix_rank(x)

3

In [32]:
x.shape

(3, 3)

In [33]:
x = np.matrix([[1,3,1],[2,2,1],[3,1,1]])

In [35]:
LA.matrix_rank(x)

2

In [37]:
A = np.matrix([[1,2],[3,4]])

In [40]:
LA.det(A)

-2.0000000000000004

In [41]:
LA.inv(A)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])